type TipType = {
  tip: string
  delay: number
}

export const tips: TipType[] = [
  { tip: 'Tailor your resume to the job description.', delay: 1000 },
  { tip: 'Research the company before your interview.', delay: 1000 },
  { tip: 'Network within your industry to find opportunities.', delay: 1000 },
  { tip: 'Practice common interview questions.', delay: 1000 },
  { tip: 'Follow up with a thank-you email after interviews.', delay: 1000 },
  { tip: 'Use LinkedIn to connect with potential employers.', delay: 1000 },
  { tip: 'Be punctual for interviews and meetings.', delay: 1000 },
  { tip: 'Dress appropriately for the job you want.', delay: 1000 },
  { tip: 'Keep your online presence professional.', delay: 1000 },
  { tip: 'Highlight your achievements, not just responsibilities.', delay: 1000 },
  { tip: 'Show enthusiasm and interest in the role.', delay: 1000 },
  { tip: 'Ask insightful questions during the interview.', delay: 1000 },
  { tip: 'Keep your resume concise and focused.', delay: 1000 },
  { tip: 'Stay organized with your job applications.', delay: 1000 },
  { tip: 'Be honest about your skills and experiences.', delay: 1000 },
  { tip: 'Prepare a strong elevator pitch.', delay: 1000 },
  { tip: 'Be ready to discuss your weaknesses.', delay: 1000 },
  { tip: 'Customize your cover letter for each application.', delay: 1000 },
  { tip: 'Practice good body language during interviews.', delay: 1000 },
  { tip: 'Keep learning and updating your skills.', delay: 1000 },
  { tip: 'Show confidence but avoid arrogance.', delay: 1000 },
  { tip: 'Use action verbs in your resume.', delay: 1000 },
  { tip: 'Be patient but persistent in your job search.', delay: 1000 },
  { tip: 'Build a portfolio to showcase your work.', delay: 1000 },
  { tip: 'Stay positive and motivated.', delay: 1000 },
  { tip: 'Prepare examples that demonstrate your skills.', delay: 1000 },
  { tip: 'Negotiate your salary confidently.', delay: 1000 },
  { tip: 'Understand the company’s culture.', delay: 1000 },
  { tip: 'Don’t be afraid to apply for jobs you’re not fully qualified for.', delay: 1000 },
  { tip: 'Use a professional email address for applications.', delay: 1000 },
  { tip: 'Be mindful of your social media activity.', delay: 1000 },
  { tip: 'Follow up if you don’t hear back within a week.', delay: 1000 },
  { tip: 'Use keywords from the job description in your resume.', delay: 1000 },
  { tip: 'Prepare for behavioral interview questions.', delay: 1000 },
  { tip: 'Be prepared to discuss your career goals.', delay: 1000 },
  { tip: 'Keep your references updated.', delay: 1000 },
  { tip: 'Maintain a professional demeanor at all times.', delay: 1000 },
  { tip: 'Use a simple, clean resume format.', delay: 1000 },
  { tip: 'Be clear and concise in your communication.', delay: 1000 },
  { tip: 'Stay calm and composed under pressure.', delay: 1000 },
  { tip: 'Avoid speaking negatively about past employers.', delay: 1000 },
  { tip: 'Show genuine interest in the company’s mission.', delay: 1000 },
  { tip: 'Bring multiple copies of your resume to the interview.', delay: 1000 },
  { tip: 'Be prepared to explain employment gaps.', delay: 1000 },
  { tip: 'Always have a list of questions for the interviewer.', delay: 1000 },
  { tip: 'Show initiative by taking on new challenges.', delay: 1000 },
  { tip: 'Be open to feedback and constructive criticism.', delay: 1000 },
  { tip: 'Be willing to relocate if necessary.', delay: 1000 },
  { tip: 'Focus on your strengths during interviews.', delay: 1000 },
  { tip: 'Keep your resume up to date.', delay: 1000 },
  { tip: 'Be yourself and let your personality shine.', delay: 1000 },
];
